In [1]:
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt

In [2]:
# dropna : drop the row with at least one element missing
df = pd.read_csv('Logistic_Reg_Infected.csv').dropna()
df

age  sleep  infected
0    1.20    5.0         0
1    2.00    5.6         0
2    2.20    6.5         0
3   12.10   10.3         1
4    6.30    5.3         0
5    6.66    6.4         0
6    7.70    7.5         0
7    7.80    7.9         0
8    8.50   10.0         0
9    9.00    9.2         1
10   9.80    9.3         1
11  10.20   10.4         1
12  10.00    8.8         0
13  12.00    9.8         1
14   4.00    9.0         0
15  12.30    8.0         1
16  13.00   11.0         0
17  14.00    9.7         1
18  18.50    8.5         1

In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
logReg = LogisticRegression(solver = 'lbfgs')
x = df[['age','sleep']]
y= df['infected']
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state =0)

In [4]:
x_train.head()

age  sleep
16  13.00   11.0
6    7.70    7.5
4    6.30    5.3
2    2.20    6.5
5    6.66    6.4

In [5]:
logReg.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [6]:
logReg.predict([[7.5,0.65]])

array([0], dtype=int64)

In [7]:
from sklearn.metrics import accuracy_score
y_pred = logReg.predict (x_test)


In [8]:
print (y_test)
print (y_pred)

10    1
1     0
8     0
18    1
14    0
Name: infected, dtype: int64
[0 0 0 1 0]


In [9]:
from sklearn.metrics import confusion_matrix
confusion_matrix (y_test, y_pred, labels = [1,0])

array([[1, 1],
       [0, 3]], dtype=int64)

In [10]:
accuracy_score(y_test, y_pred)

0.8